// lib/Models/customer_model.dart

class CustomerModel {
  String id; // local uuid (offline key)

  // ── Who added this customer (logged-in employee) ─────────────────────
  String empId;
  String empName;
  String? companyCode;

  // ── Customer detail ────────────────────────────────────────────────
  String? customerNo; // Auto-generated by DB trigger: CU-YYYY-XXXX
  String name;
  String mobile;
  String email;
  String cnic;        // CNIC stored in REMARKS or separate field
  String address;
  String altMobile;   // Additional mobile number
  String city;
  String remarks;     // Can store CNIC, notes, etc.
  bool posted;

  CustomerModel({
    required this.id,
    this.empId = '',
    this.empName = '',
    this.companyCode,
    this.customerNo,
    this.name = '',
    this.mobile = '',
    this.email = '',
    this.cnic = '',
    this.address = '',
    this.altMobile = '',
    this.city = '',
    this.remarks = '',
    this.posted = false,
  });

  // ── Getter for initials (used for avatar display) ──────────────────
  String get initials {
    final n = name.trim();
    if (n.isEmpty) return '?';
    final parts = n.split(' ').where((p) => p.isNotEmpty).toList();
    if (parts.length >= 2) {
      return '${parts[0][0]}${parts[1][0]}'.toUpperCase();
    }
    return n[0].toUpperCase();
  }

  // ── Local (SharedPreferences) JSON ─────────────────────────────────
  Map<String, dynamic> toJson() => {
    'id': id,
    'empId': empId,
    'empName': empName,
    'companyCode': companyCode,
    'customerNo': customerNo,
    'name': name,
    'mobile': mobile,
    'email': email,
    'cnic': cnic,
    'address': address,
    'altMobile': altMobile,
    'city': city,
    'remarks': remarks,
    'posted': posted,
  };

  factory CustomerModel.fromJson(Map<String, dynamic> j) => CustomerModel(
    id: j['id']?.toString() ?? '',
    empId: j['empId']?.toString() ?? '',
    empName: j['empName']?.toString() ?? '',
    companyCode: j['companyCode']?.toString(),
    customerNo: j['customerNo']?.toString(),
    name: j['name']?.toString() ?? '',
    mobile: j['mobile']?.toString() ?? '',
    email: j['email']?.toString() ?? '',
    cnic: j['cnic']?.toString() ?? '',
    address: j['address']?.toString() ?? '',
    altMobile: j['altMobile']?.toString() ?? '',
    city: j['city']?.toString() ?? '',
    remarks: j['remarks']?.toString() ?? '',
    posted: j['posted'] == true,
  );

  // ── APEX / ORDS JSON ────────────────────────────────────────────────
  // Matches CRM_CUSTOMERS table columns (customer_no is auto-generated)
  Map<String, dynamic> toApexJson() => {
    'customer_name': name,
    'mobile_number': mobile,
    'alt_mobile': altMobile,
    'email': email,
    'address': address,
    'city': city,
    'remarks': remarks.isNotEmpty ? remarks : (cnic.isNotEmpty ? 'CNIC: $cnic' : ''),
    'emp_id': empId,
    'emp_name': empName,
    'company_code': companyCode,
  };
}